### PR TITLE
test case for long URLs: fails

### LINKED ISSUE #102: URLs containing special characters in the query string cause errors
When there are special characters like `.` in the query string, helix simulator will include them in parsing the selector and extension, which leads to files that cannot be found. The problem manifested itself in a scenario where a client token got passed back from an OAuth API.

### PR DESCRIPTION
**Pull request by hirenoble**
I've encountered an error in local simulation when working with long URLs (generated by an OAuth dance). `hlx up` will fail with an error message: 

```
Error: ENAMETOOLONG: name too long, open '/Users/hireshah/helix-6/analytics.html?client_id=5a8d…
```

This PR introduces a test case for Helix Simulator that reproduces that error and fixes it.

Fixes #102

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ const utils = {
   async fetch(uri, logger) {
     if (uri.charAt(0) === '/') {
       try {
-        return await fs.readFile(uri);
+        return await fs.readFile(uri.replace(/\?.*$/, ''));
```
Comment (tripodsan) [inline src/utils.js]: i would probably be better to just pass in the path and not the entire uri

File: test/hlx_server_test.js [hunk 2]
```diff
@@ -122,6 +122,21 @@ describe('Helix Server', () => {
...
...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&xxxxxx=xxxxxxxx|xxxxxxx|xxxxxxxx&xxxxxxxxxxxxx=xxxxx%xxxx|xxxxx%xxxxxxxxx%xxxxxxxxxxxx|xxxxx-xx-xxxxxxxxx-xxxx`, 200, 'expected_index.html');
```
Comment (tripodsan) [inline test/hlx_server_test.js]: do you really need such a large query string to test this bug ?  :-)

Comment (trieloff) [reply test/hlx_server_test.js]: The query string is a real-life OAuth API response (with all characters and digits replaced with `x`), so it might not be super necessary, but it is very realistic.

File: src/utils.js (hunk 1 above)
Comment (trieloff) [reply src/utils.js]: `uri` is the path in this case.

Comment (trieloff) [reply src/utils.js]: Do you mean to change `uri` to `uriOrPath` in line 38?

Comment (hirenoble) [reply src/utils.js]: @trieloff Changed uri to uriOrPath
